### ISSUE TITLE
though it still needs to load all keys to memory

### ISSUE THREAD

**Issue by sgf** [Bobris/BTDB#111]
Is it expected to improve. Because in fact, under big data, loading all keys will make the usage scenario very limited.

I am currently looking for a KV Store. It is precisely because of the limited memory and hard disk space that 20 billion keys need to be stored, but the value is not large, and the value does not need to be indexed.

my key about MaxLength 50 characters string (dynamic length).
and the value MaxLength  about 50 bytes.

The production environment does not have huge memory. It is possible that the data storage area can only use memory below 512mb.

**Comment by Bobris** [comment]
BTDB is not expect to be improved in this space it is targeting OLTP usecases where you can reasonably partition/shard data. (In production is it used with 110GB of RAM, DB actually using only 1/3 of that space).

But if I understand you right you actually need Persistent HashMap. You could probably implement that on top of BTDB, key would be just part of hash - and value would be all keys and values serialised (all of that with that same hash). Depending on quality of your hash maximum sizes of such values could be relatively small. But probably some specialised data structure would be even better.

**Comment by sgf** [comment]
thanks
