### ISSUE TITLE
Compatibility of - Implement properly selfreferencing storedinline objects

### ISSUE THREAD

**Issue by karasek** [Bobris/BTDB#41]
3.5.0.0 version failed to load data stored by 3.4.0.0 version

when loading object

        [StoredInline]
        public class NetServerPackageItem
        {
            public string SourceFile { get; set; }
            public string Version { get; set; }
            public string Comment { get; set; }
            public BlobLocation BlobLocation { get; set; }
            public DateTime UploadStartTime { get; set; }
            public DateTime UploadFinishedTime { get; set; }
            public ulong UserId { get; set; }
            public string UserName { get; set; }
            public double Progress { get; set; }
            public bool Finished { get; set; }
            public bool Preferred { get; set; }
        }

        [StoredInline]
        public class BlobLocation
        {
            public string Prefix { get; set; }
            public string Name { get; set; }
            public ulong EncryptKeyId { get; set; }
        }

ReadNativeObject() (in bold below) gets parent object from cache (as index 0) - because it has different DB context object cache than during save? And then the byte content of BlobLocation is not readed and when interpreting as consecutive DateTime fields fails

static void Loader_NetServerPackageItem_1(
    BTDB.ODBLayer.IInternalObjectDBTransaction arg0,
    BTDB.ODBLayer.DBObjectMetadata arg1,
    BTDB.StreamLayer.AbstractBufferedReader arg2,
    object arg3)
{
    Gmc.Inachis.InspireProcessing.NetServerPackageDeployment.Db.NetServerPackageItem local0 // index 0
    ldarg.3
    castclass Gmc.Inachis.InspireProcessing.NetServerPackageDeployment.Db.NetServerPackageItem
    stloc.0
    BTDB.FieldHandler.IReaderCtx local1 // index 1
    ldarg.0
    ldarg.2
    callvirt BTDB.FieldHandler.IReaderCtx GetReaderCtx(BTDB.StreamLayer.AbstractBufferedReader reader)
    stloc.1
    ldloc.0
    ldarg.2
    call string ReadString()
    call void set_SourceFile(string value)
    ldloc.0
    ldarg.2
    call string ReadString()
    call void set_Version(string value)
    ldloc.0
    ldarg.2
    call string ReadString()
    call void set_Comment(string value)
    ldloc.0
    ldloc.1
    **callvirt object ReadNativeObject()**
    isinst Gmc.Cloud.Infrastructure.Host.BlobLocation  //is not set - it is NetServerPackageItem
    call void set_BlobLocation(Gmc.Cloud.Infrastructure.Host.BlobLocation value)
    ldloc.0
    ldarg.2
    **call System.DateTime ReadDateTime()**
    call void set_UploadStartTime(System.DateTime value)
    ldloc.0
    ldarg.2
    call System.DateTime ReadDateTime()
    call void set_UploadFinishedTime(System.DateTime value)

**Comment by Bobris** [comment]
Reverted in 3.6.0.0 it will need huge amount of code to fix it properly :frowning:
