### ISSUE TITLE
Does BTDB compile and run in a UWP App?

### ISSUE THREAD

**Issue by 10Dev** [Bobris/BTDB#42]
Does BTDB compile and run in a UWP App?

Sometimes when .NET 4.5 is mentioned as the target, a project will work on UWP and sometimes not.

So it would be nice if you could add a note to the main page one way or the other.

If the answer is no, then perhaps re-title this issue as "UWP Porting"

**Comment by Bobris** [comment]
BTDB heavily use runtime code generation (Reflection.Emit) which makes it no go for UWP Apps.
I don't see way how to workaround that, so closing this as basically unrealistic.
